#pragma once

#include "Effect.h"

BEGIN(Engine)
class CModel;
class CShader;
END

BEGIN(Client)

typedef struct tagBillboardValueFixEffectDesc
{
	tagBillboardValueFixEffectDesc() = default;
	tagBillboardValueFixEffectDesc(EFFECTDESC _EffDesc, SUB_EFFECT_DESC _SubEffDesc)
		: EffectDesc(_EffDesc)
		, SubEffectDesc(_SubEffDesc) {}

	EFFECTDESC			EffectDesc;
	SUB_EFFECT_DESC		SubEffectDesc;
	_float				fRoll = 0.f, fPitch = 0.f, fYaw = 0.f;
	_float				fValueX = 0.f, fValueY = 0.f, fValueZ = 0.f;
	_bool				bMove = false;
	_float				fTimeX = 0.f, fTimeY = 0.f, fTimeZ = 0.f;
}VALUEFIXEFFECTDESC;

#pragma region DEFINE

#define	EFFECT_MAY_BURSTHIT0 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_BURSTHIT, EFFECT_SUBDESC_MAY_BURSTHIT0)
#define	EFFECT_MAY_BURSTHIT1 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_BURSTHIT, EFFECT_SUBDESC_MAY_BURSTHIT1)
#define	EFFECT_MAY_BURSTHIT2 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_BURSTHIT, EFFECT_SUBDESC_MAY_BURSTHIT2)
#define	EFFECT_MAY_SLASHSPARK01 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_SLASHSPARK, EFFECT_SUBDESC_MAY_SLASHSPARK01)
#define	EFFECT_MAY_SLASHSPARK02 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_SLASHSPARK, EFFECT_SUBDESC_MAY_SLASHSPARK02)
#define	EFFECT_MAY_SLASHSPARK03 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_SLASHSPARK, EFFECT_SUBDESC_MAY_SLASHSPARK03)
#define	EFFECT_MAY_SLASHSPARK05 VALUEFIXEFFECTDESC(EFFECT_DESC_MAY_SLASHSPARK, EFFECT_SUBDESC_MAY_SLASHSPARK05)
#define	EFFECT_GOS_SPLASH01 VALUEFIXEFFECTDESC(EFFECT_DESC_GOS_SPLASH01, EFFECT_SUBDESC_GOS_SPLASH01)
#define	EFFECT_GOS_SPLASH02 VALUEFIXEFFECTDESC(EFFECT_DESC_GOS_SPLASH02, EFFECT_SUBDESC_GOS_SPLASH02)
#define	EFFECT_GOS_WATERRING VALUEFIXEFFECTDESC(EFFECT_DESC_GOS_WATERRING, EFFECT_SUBDESC_GOS_WATERRING)
#define	EFFECT_BKN_SANJU_TENCHIJIN	VALUEFIXEFFECTDESC(EFFECT_DESC_BKN_SANJU_TENCHIJIN, EFFECT_SUBDESC_BKN_SANJU_TENCHIJIN)
#define	EFFECT_BKN_SANJU_TENCHIJINREVERSE	VALUEFIXEFFECTDESC(EFFECT_DESC_BKN_SANJU_TENCHIJIN, EFFECT_SUBDESC_BKN_SANJU_TENCHIJINREVERSE)
#define	EFFECT_BKN_SANJU_TENCHIJINANIM	VALUEFIXEFFECTDESC(EFFECT_DESC_BKN_SANJU_TENCHIJINANIM, EFFECT_SUBDESC_BKN_SANJU_TENCHIJINANIM)
#define	EFFECT_BKN_SANJU_TENCHIJINANIMREVERSE	VALUEFIXEFFECTDESC(EFFECT_DESC_BKN_SANJU_TENCHIJINANIM, EFFECT_SUBDESC_BKN_SANJU_TENCHIJINANIMREVERSE)
#define EFFECT_BKN_DUSTSMOKE	VALUEFIXEFFECTDESC(EFFECT_DESC_BKN_DUSTSMOKE, EFFECT_SUBDESC_BKN_DUSTSMOKE)
#define EFFECT_BGT_ROGERSPEEDLINE	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_ROGERSPEEDLINE, EFFECT_SUBDESC_BGT_ROGERSPEEDLINE)
#define EFFECT_BGT_KSMH_YOYOSPARK01	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOSPARK, EFFECT_SUBDESC_BGT_KSMH_YOYOSPARK01)
#define EFFECT_BGT_KSMH_YOYOSPARK02	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOSPARK, EFFECT_SUBDESC_BGT_KSMH_YOYOSPARK02)
#define EFFECT_BGT_KSMH_YOYOLINE01	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOLINE, EFFECT_SUBDESC_BGT_KSMH_YOYOLINE01)
#define EFFECT_BGT_KSMH_YOYOLINE02	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOLINE, EFFECT_SUBDESC_BGT_KSMH_YOYOLINE02)
#define EFFECT_BGT_KSMH_YOYOSTRING01	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOSTRING, EFFECT_SUBDESC_BGT_KSMH_YOYOSTRING01)
#define EFFECT_BGT_KSMH_YOYOSTRING02	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_YOYOSTRING, EFFECT_SUBDESC_BGT_KSMH_YOYOSTRING02)
#define EFFECT_BGT_KSMH_SPARK01	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_SPARK01, EFFECT_SUBDESC_BGT_KSMH_SPARK01)
#define EFFECT_BGT_KSMH_SPARK02	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_SPARK02, EFFECT_SUBDESC_BGT_KSMH_SPARK02)
#define EFFECT_BGT_KSMH_SPARKLINE01	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_SPARKLINE01, EFFECT_SUBDESC_BGT_KSMH_SPARKLINE01)
#define EFFECT_BGT_KSMH_SPARKLINE02	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_KSMH_SPARKLINE02, EFFECT_SUBDESC_BGT_KSMH_SPARKLINE02)
#define EFFECT_BGT_RKM_SMOKE	VALUEFIXEFFECTDESC(EFFECT_DESC_BGT_RKM_SMOKE, EFFECT_SUBDESC_BGT_RKM_SMOKE)

#pragma endregion

class CEffect_BillboardValueFix_Effect : public CEffect
{
protected:
	explicit CEffect_BillboardValueFix_Effect(ID3D11Device* pDevice, ID3D11DeviceContext* pDeviceContext);
	explicit CEffect_BillboardValueFix_Effect(const CEffect_BillboardValueFix_Effect& rhs);
	virtual ~CEffect_BillboardValueFix_Effect() = default;

public:
	virtual HRESULT								NativeConstruct_Prototype();
	virtual HRESULT								NativeConstruct(void* pArg);
	virtual _int								Tick(_double TimeDelta);
	virtual _int								LateTick(_double TimeDelta);
	virtual HRESULT								Render();

protected:
	HRESULT										SetUp_ConstantTable_BillBoarding();

protected:
	CShader*									m_pShaderCom = nullptr;
	CModel*										m_pModelCom = nullptr;
	VALUEFIXEFFECTDESC							m_ValueFixDesc;
	_float										m_fTimeDeltaX = 0.f, m_fTimeDeltaY = 0.f, m_fTimeDeltaZ = 0.f;

public:
	static	CEffect_BillboardValueFix_Effect*	Create(ID3D11Device* pDevice, ID3D11DeviceContext* pDeviceContext);
	virtual CGameObject*						Clone(void* pArg);
	virtual void								Free() override;

};

END